### ISSUE TITLE
`eslint-plugin-react` is required even if rule is not specified in .eslintrc

### ISSUE THREAD

**Issue by eastenluis** [tophat/eslint-config#50]
Eslint-config version: 0.3.1
Related PR: https://github.com/tophat/sanity-runner/pull/131

I am updating sanity runner to use the latest eslint-config. However, running lint gives me following error message:

```
ESLint: 5.9.0.
ESLint couldn't find the plugin "eslint-plugin-react". This can happen for a couple different reasons:
...
```

Sanity runner does not contain any React codes, hence it does not make sense to require `eslint-plugin-react` in the package. Besides, it is not set as a peer dependency in the package.json, so it really shouldn't break lint in that package.

**Comment by msrose** [comment]
You have to change the eslint config to extend `@tophat/eslint-config/base` instead of `@tophat`. The upgrade instructions are provided in the changelog: https://github.com/nodejs/node/commit/796f3d0af49164314868c4778af90eca356f1fef. It is a strange error in this case, but it shouldn't require the react plugin if you don't extend the default or react configs.

**Comment by msrose** [comment]
Sorry had the wrong link initially, I've updated it now.

**Comment by eastenluis** [comment]
@msrose Thanks it works! Though I got a different lint issues now. Will research a bit more 😂
